# Generated by Django 4.0.2 on 2022-11-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cancellation_reason',
            field=models.CharField(max_length=100),
        ),
    ]
