# Generated by Django 4.1.3 on 2022-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_flight_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airline",
            field=models.IntegerField(default=0),
        ),
    ]
