# Generated by Django 4.1.3 on 2022-11-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_flight_airline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="scheduled_arrival",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="scheduled_departure",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="wheels_off",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="wheels_on",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
