# Generated by Django 4.1.3 on 2022-11-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_flight_arrival_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airline",
            name="airline",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="airline",
            name="iata_code",
            field=models.CharField(default="XXX", max_length=3),
        ),
        migrations.AlterField(
            model_name="airport",
            name="airport",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="airport",
            name="iata_code",
            field=models.CharField(default="XXX", max_length=3),
        ),
    ]
