# Generated by Django 4.0.2 on 2022-11-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airline_rename_airline_airport_airport_airport_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('day_of_week', models.IntegerField(default=0)),
                ('flight_number', models.IntegerField(default=0)),
                ('tail_number', models.CharField(default='', max_length=100)),
                ('scheduled_departure', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('departure_delay', models.IntegerField(default=0)),
                ('taxi_out', models.IntegerField(default=0)),
                ('wheels_off', models.TimeField()),
                ('scheduled_time', models.IntegerField(default=0)),
                ('elapsed_time', models.IntegerField(default=0)),
                ('air_time', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('wheels_on', models.TimeField()),
                ('taxi_in', models.IntegerField(default=0)),
                ('scheduled_arrival', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('arrival_delay', models.IntegerField(default=0)),
                ('diverted', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.CharField(default='', max_length=100)),
                ('air_system_delay', models.IntegerField(default=0)),
                ('security_delay', models.IntegerField(default=0)),
                ('airline_delay', models.IntegerField(default=0)),
                ('late_aircraft_delay', models.IntegerField(default=0)),
                ('weather_delay', models.IntegerField(default=0)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airline')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='api.airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_airport', to='api.airport')),
            ],
        ),
    ]
